# Generated by Django 3.2 on 2021-04-27 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_alter_blog_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2021, 4, 27, 11, 37, 0, 965189)),
        ),
    ]
