# Generated by Django 3.2 on 2021-04-27 11:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_blog_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2021, 4, 27, 11, 37, 41, 815, tzinfo=utc)),
        ),
    ]
