# Generated by Django 3.2 on 2021-04-27 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_alter_blog_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_create',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
